server:
  port: 8901

spring:
  application:
    name: babi-langgraph4j

babi:
  agent:
    workspace: ~/babi-workspace
    model:
      name: qwen-plus
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DASHSCOPE_API_KEY:}
