server:
  port: 8901

spring:
  application:
    name: babi-langgraph4j

babi:
  agent:
    workspace: ~/babi-workspace
    model:
      name: deepseek-v4-flash
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY:}
